available_text_models: ["gpt-3.5-turbo", "gpt-3.5-turbo-16k", "gpt-4", "text-davinci-003"]

info:
  gpt-3.5-turbo:
    type: chat_completion
    name: ChatGPT
    description: ChatGPT - это хорошо известная модель. Она <b>быстрая</b> и <b>дешёвая</b>. Идеально подходит для повседневных задач. Если есть задачи, с которыми она не может справиться, попробуйте <b>GPT-4</b>.

    price_per_1000_input_tokens: 0.0015
    price_per_1000_output_tokens: 0.002

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  gpt-3.5-turbo-16k:
    type: chat_completion
    name: GPT-16K
    description: ChatGPT - это хорошо известная модель. Она <b>быстрая</b> и <b>дешёвая</b>. Идеально подходит для повседневных задач. Если есть задачи, с которыми она не может справиться, попробуйте <b>GPT-4</b>.

    price_per_1000_input_tokens: 0.003
    price_per_1000_output_tokens: 0.004

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  gpt-4:
    type: chat_completion
    name: GPT-4
    description: GPT-4 - наиболее <b>умная</b> и самая продвинутая модель в мире. Но она медленнее и не такая экономичная в сравнении с ChatGPT. Лучший выбор для <b>сложных</b> интеллектуальных задач.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      Smart: 5
      Fast: 2
      Cheap: 2

  text-davinci-003:
    type: completion
    name: GPT-3.5
    description: GPT-3.5 - устаревшая модель. На самом деле <b>нет смысла использовать её</b>, потому что она дороже и медленнее в сравнении с ChatGPT, но примерно такая же умная.

    price_per_1000_input_tokens: 0.02
    price_per_1000_output_tokens: 0.02

    scores:
      Smart: 3
      Fast: 2
      Cheap: 3

  dalle-2:
     type: image
     price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006
